# Get-Started

## 数据表示

- 特征矩阵（Feature Matrix）：每一行代表一个数据样本，每一列代表一个特征（即输入变量）;它是一个二维的数组或矩阵，通常使用 NumPy 数组或 pandas DataFrame 来存储。
- 目标向量（Target Vector）：它表示每个样本的目标（即输出标签），通常是一个一维数组。

- 特征（Features）：是数据集中用于训练模型的输入变量。在上面的例子中，X 是特征矩阵，包含了所有的输入变量。

- 标签（Labels）：是机器学习模型的目标输出。在监督学习中，标签是我们希望模型预测的结果。在上面的例子中，y 是标签或目标向量，包含了每个样本的类别。

In [20]:
import numpy as np

X = np.array([[1.,2.],[2.,3.],[3.,4.]])
y = np.array([0,1,0])

print(X.shape,y.shape)

(3, 2) (3,)


## 数据集分割

In [21]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)


X_train.shape,y_train.shape

((2, 2), (2,))

## 预处理和特征工程

- 标准化（Standardization）：特征的尺度统一，使得每个特征都具有**零均值和单位方差**。
- 归一化（Normalization）：将特征的值缩放到一个**固定范围**（通常是 0 到 1）。

In [22]:
# 引入
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
X

array([[1., 2.],
       [2., 3.],
       [3., 4.]])

In [ ]:
# 标准化
#with_mean=True 在缩放前对每个特征进行中心化（减去均值）。对于稀疏矩阵应设为 False，以避免破坏稀疏结构。
#with_std=True 将每个特征除以其标准差，使其方差为 1。如果设为 False，则只做中心化不缩放。

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-1.22474487, -1.22474487],
       [ 0.        ,  0.        ],
       [ 1.22474487,  1.22474487]])

In [24]:
# 归一化
scaler = MinMaxScaler()
X_normalized = scaler.fit_transform(X)
X_normalized

array([[0. , 0. ],
       [0.5, 0.5],
       [1. , 1. ]])

# 机器学习模型

- 分类模型（Classification）：预测离散类别
- 回归模型（Regression）：预测连续数值
- 聚类模型（Clustering）：对数据进行自动分组（无监督学习）

## 回归模型

### 线性回归

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# 假设 X 是特征矩阵，y 是目标变量
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

# 预测
y_pred = model.predict(X_test)

